2024-11-25 17:46:24,357 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179ea8f40>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 17:46:24,425 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179eaa540>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 17:46:24,473 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179ebb5c0>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 17:46:24,503 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e217a081d80>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 17:46:26,534 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179ec5740>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 17:57:04,862 INFO: Auth service startup
Details: None
Path: /home/michael/Desktop/skill3/skill3/app.py:67

2024-11-25 18:11:20,075 INFO: Auth service startup
Details: None
Path: /home/michael/Desktop/skill3/skill3/app.py:73

2024-11-25 18:23:50,350 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179ec7b40>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 20:26:09,551 ERROR: Unexpected error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Details: (<class 'werkzeug.exceptions.NotFound'>, <NotFound '404: Not Found'>, <traceback object at 0x7e2179ec6fc0>)
Path: /home/michael/Desktop/skill3/skill3/app.py:85
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/michael/.local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/home/michael/.local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/michael/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
